"""Post table

Revision ID: 498c6fbd80a6
Revises: 6379879e1213
Create Date: 2018-05-28 12:41:50.749314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '498c6fbd80a6'
down_revision = '6379879e1213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postDAO',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=180), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['userDAO.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postDAO_timestamp'), 'postDAO', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_postDAO_timestamp'), table_name='postDAO')
    op.drop_table('postDAO')
    # ### end Alembic commands ###
